### PR TITLE
use async/await; add jest + babel w/ babel-preset-env

### PR DESCRIPTION
**Pull request by DSchau**
A lot of this is opinionated rather than substantive changes, but since I was working on something similar in [screenie](https://github.com/DSchau/screenie/tree/master/packages/screenie), figured I'd help out!

# Change Overview

- Added babel/babel-preset-env to target Node 6.4.0 (package.json engines field)
- Added async/await to avoid unnecessary promise chain
- Switched testing library to jest
- Created a src/ folder and now build transpiled files to lib/ (including both the tool itself and the CLI)

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@DSchau -- Thanks for the interest in this project!

@kenwheeler and I already made the decision to code this as actual node. (Backstory -- node sourcemaps support is still terrible, so we follow the adage of "run the code you write"). Our long term plan is to write code that supports maintained node. Which means unfortunately promises until node 6 is end-of-life'd.

We're also considering whether or not to keep `puppeteer`. It's a **fantastic** library, but currently is not really compatible with environments like serverlesss, whereas more bare-metal stuff like `chrome-remote-interface` with a simple chromium launcher is super slim. Turns out that we don't need that much client sophistication for a PDF rendered for Spectacle.

Also, for `jest` we typically don't use this for node tests. I don't really see anything uniquely valuable added over Mocha. If there is something specific here, then we'd be open to a switch -- just not switching to jest "because".

So, I'd say for sure:

* [ ] Remove babel -- revert to real untranspiled code

If you'd like

* [ ] Propose benefits for switching to jest for us to consider over mocha.

... and we can chat things further from there. Thanks!

**Comment by DSchau** [comment]
Hi @ryan-roemer! Of course! Big fan of spectacle, so definitely interested in this project :)

Lots of interesting stuff here, sincere thanks for the detailed reply!

> Our long term plan is to write code that supports maintained node. Which means unfortunately promises until node 6 is end-of-life'd.

The code is transpiled to support _exactly_ what node 6.4.0 supports (in this case async/await is transpiled to generators, `yield` statements, and `Promise`s), but am I correct in understanding that sourcemaps (rather, the lack thereof) are the deal-breaker here? Is this primarily useful for debugging and troubleshooting?

Glad I didn't go with ES imports/exports ;) 

> We're also considering whether or not to keep puppeteer. It's a fantastic library, but currently is not really compatible with environments like serverlesss, whereas more bare-metal stuff like chrome-remote-interface with a simple chromium launcher is super slim. Turns out that we don't need that much client sophistication for a PDF rendered for Spectacle.

Interesting! Hadn't actually heard of that library, but I'll definitely be checking it out. Have you considered whether it might make sense to generate individual .png (or .jpeg) files for each slide in the slide deck, as well? I wanted to do something similar to what [Phil did here](https://medium.com/styled-components/with-styled-components-into-the-future-d1d917e7c22c) with his blog post, but of course, for Spectacle.

> I don't really see anything uniquely valuable added over Mocha

Fair point! I think there are some inherent benefits to using one library for React testing _and_ for Node utility testing (especially if there are not significant qualitative differences between the two libraries), but you are correct that this PR does not adequately express really _any_ of some real benefits of Jest and feels a bit like change for the sake of change.

Would you be interested in a PR that demonstrates some of the benefits of jest over Mocha? Some things that come to mind would be:

- Utilizing jest's excellent mocking (e.g. mocking the entire puppetteer library in a certain test suite) to validate correct inputs
- Utilizing jest's snapshot feature to do something like validate generated content--unfortunately not seeing anything for PDFs, but if PNGs are ever generated, would work great :)

There are some other benefits (great interactive watch mode including only running tests on changed files, specific files, etc.) but many of them arise when writing _more_ tests, as well as some more unit tests. I'm not sure many of those benefits would be realized with a smaller test suite of primarily integration tests.

**Comment by ryan-roemer** [comment]
## Node vs. Babel

> am I correct in understanding that sourcemaps (rather, the lack thereof) are the deal-breaker here? Is this primarily useful for debugging and troubleshooting?

Yes. We have a strong general bias for "run code you write" in node-land. In this specific case even moreso, because the babel output of async/await stuff is really convoluted. And the current promise version doesn't read that much harder than the async/await version.

## Individual Slides

> Have you considered whether it might make sense to generate individual .png (or .jpeg) files for each slide in the slide deck, as well?

Hadn't considered that! @kenwheeler might want to add that to the roadmap!

## Tests

I'm OK with whatever Ken wants for tests and such. Right now, the two things counseling perhaps against a Jest switch are:

1. We might change the API / underlying libraries a lot in the near future.
2. We don't have anything React/snapshot specific to test against.

Another useful thing to consider on the flipside of things is that the wonderful combination of Mocha + Chai + Sinon can fully test:

* frontend unit tests
* backend unit tests
* backend REST function tests (with a client like superagent)
* full browser functional tests (with a client like webdriverio)

We've successfully used this "full one-stop shopping" stack for years, and with React apps. Personally, I find the natural language / huge API of Chai assertions better for writing good, terse asserts that fail informatively. The snapshotting feature of Jest is the one big advantage of the framework, but I'm guessing snapshotting will find its way out into the general ecosystem in the future.

But that's my personal bias -- and I'm an old-school testing curgmudgeon -- I'm perfectly happy with any test stack that Ken wants 😄

**Comment by DSchau** [comment]
### Node v. Babel

I'll concede this! I definitely agree that how the library is authored now, the promise chain doesn't look that much worse, nor will it be _necessarily_ harder to maintain. If the library grows, that might no longer be the case, but that's extremely hard to predict and prove. The "native Node" approach is really interesting, and I actually do like the simplicity of it!

### Testing & Jest

> We don't have anything React/snapshot specific to test against.

More of a theoretical benefit, rather than a tangible one now, so fair point!

#### "... Mocha + Chai + Sinon can fully test [X, Y, Z]"

That's true! But so can Jest! It even ships with a Node env setting (disables jsdom) that I _entirely_ forgot to enable.

Totally agree on the value of chai terseness and readability. That said, you can continue to use [chai assertions](https://facebook.github.io/jest/docs/en/migration-guide.html) with jest (3rd bullet point).

All that said though, I didn't author this library, so there's very little point inserting (my) personal preference where it doesn't belong! Definitely think there's some value in checking out Jest, so maybe give it a spin on some future project if you haven't already.

I'll close this, but really enjoyed the discussion; thanks!

**Pull request closed without merging**
